---
window:
  dynamic_padding: true
  padding:
    x: 4
    y: 4
  startup_mode: Fullscreen

scrolling:
  history: 100000

font:
  normal:
    family: "Hack Nerd Font Mono"
    style: "Regular"
  italic:
    family: "Hack Nerd Font Mono"
    style: "Italic"
  bold:
    family: "Hack Nerd Font Mono"
    style: "Bold"
  bold_italic:
    family: "Hack Nerd Font Mono"
    style: "Bold Italic"
  size: 12

# Colors (Wilmersdorf)
colors:
  bright:
    black: '#434750'
    blue: '#b2cff0'
    cyan: '#69abc5'
    green: '#8fd7d6'
    magenta: '#efccfd'
    red: '#fa7193'
    white: '#d3d3d3'
    yellow: '#d1dfff'
  cursor:
    cursor: '#7ebebd'
    text: '#1f2024'
  normal:
    black: '#34373e'
    blue: '#a6c1e0'
    cyan: '#5b94ab'
    green: '#7ebebd'
    magenta: '#e1c1ee'
    red: '#e06383'
    white: '#ababab'
    yellow: '#cccccc'
  primary:
    background: '#282b33'
    foreground: '#c6c6c6'
  selection:
    background: '#1f2024'
    text: '#c6c6c6'

cursor:
  style:
    blinking: "Always"
    shape: "Beam"
  thickness: 0.25
  unfocused_hollow: false

key_bindings:
  - {key: Return, mods: Command, action: ToggleFullscreen}
  - {key: Key0, mods: Command, action: ResetFontSize}
  # delete line
  - {key: Back, mods: Command, chars: "\x15"}
  # delete word
  - {key: Back, mods: Option, chars: "\x1b\x7f"}
  # go to beginning of line
  - {key: Left, mods: Command, chars: "\x01"}
  # go to end of line
  - {key: Right, mods: Command, chars: "\x05"}
  # go back one word
  - {key: Left, mods: Option, chars: "\x1Bb"}
  # go forward one word
  - {key: Right, mods: Option, chars: "\x1Bf"}

  # tmux keybindings
  # create new window
  - {key: T, mods: Command, chars: "\x02\x63"}
  # break current tmux pane out of the tmux window
  - {key: T, mods: Command|Shift, chars: "\x02\x21"}
  # delete current window
  - {key: W, mods: Command, chars: "\x02\x77"}
  # split pane vertically
  - {key: D, mods: Command, chars: "\x02\x25"}
  # split pane horizontally
  - {key: D, mods: Command|Shift, chars: "\x02\x22"}
  # go to previous window
  - {key: Left, mods: Command|Option, chars: "\x02\x70"}
  # go to next window
  - {key: Right, mods: Command|Option, chars: "\x02\x6e"}
  # list sessions
  - {key: L, mods: Command, chars: "\x02\x73"}
  # swap windows going left
  - {key: Comma, mods: Command, chars: "\x02\x2c"}
  # swap windows going right
  - {key: Period, mods: Command, chars: "\x02\x2e"}

  # clear history
  - {key: K, mods: Control, chars: "\x02\x0b"}

  # cycle panes
  - {key: LBracket, mods: Command|Option, chars: "\x02\x4f"}
  - {key: RBracket, mods: Command|Option, chars: "\x02\x6f"}

  # cycle through windows 1-9
  - {key: Key1, mods: Command, chars: "\x02\x31"}
  - {key: Key2, mods: Command, chars: "\x02\x32"}
  - {key: Key3, mods: Command, chars: "\x02\x33"}
  - {key: Key4, mods: Command, chars: "\x02\x34"}
  - {key: Key5, mods: Command, chars: "\x02\x35"}
  - {key: Key6, mods: Command, chars: "\x02\x36"}
  - {key: Key7, mods: Command, chars: "\x02\x37"}
  - {key: Key8, mods: Command, chars: "\x02\x38"}
  - {key: Key9, mods: Command, chars: "\x02\x39"}
