[colors]
[colors.primary]
background = "#FCFBF9"
foreground = "#605A52"

[colors.normal]
black = "#DDDBD8"
white = "#7F7A73"
red = "#e1c1ee"
green = "#5b94ab"
yellow = "#cfcf9c"
blue = "#819cd6"
magenta = "#a6c1e0"
cyan = "#7289bc"

[colors.selection]
background = "#CCB9C7"

[colors.cursor]
cursor = "#7686A9"
