[colors]
[colors.primary]
background = "#ffffff"
foreground = "#635e58"

[colors.normal]
black = "#e0dfde"
white = "#827e79"
red = "#925a58"
green = "#777f53"
yellow = "#8b6e4a"
blue = "#586d9b"
magenta = "#865b83"
cyan = "#4a7e81"

[colors.selection]
background = "#cfbdcd"

[colors.cursor]
cursor = "#798aaf"
